---
  - name: Add nginx repository key
    apt_key: id=C300EE8C url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x00A6F0A3C300EE8C" state=present

  - name: Add nginx repository
    apt_repository: repo='deb http://ppa.launchpad.net/nginx/stable/ubuntu lucid main' update_cache=yes state=present

  - name: Install latest nginx
    apt: pkg=nginx state=latest

  - name: Copy subfolder project config
    template: src=symfony-subfolder.conf.j2 dest=/etc/nginx/sites-available/{{ subfolder_project_host }}

  - name: Copy subdomain project config
    template: src=symfony-subdomain.conf.j2 dest=/etc/nginx/sites-available/{{ item.name }}.{{ subdomain_project_host }}
    with_items: projects.sf2host

  - name: Add subfolder projects to sites-enabled
    file: src=/etc/nginx/sites-available/{{ subfolder_project_host }} dest=/etc/nginx/sites-enabled/{{ subfolder_project_host }} state=link
    notify:
      - nginx-reload

  - name: Add subdomain projects to sites-enabled
    file: src=/etc/nginx/sites-available/{{ item.name }}.{{ subdomain_project_host }} dest=/etc/nginx/sites-enabled/{{ item.name }}.{{ subdomain_project_host }} state=link
    with_items: projects.sf2host
    notify:
      - nginx-reload

  - name: Make sure nginx service started
    service: name=nginx state=started
