---
  - name: Add mongo repository key
    apt_key: id=7F0CEB10 url="http://docs.mongodb.org/10gen-gpg-key.asc" state=present

  - name: Add mongo repository
    apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' update_cache=yes state=present

  - name: Install latest stable mongodb
    apt: pkg=mongodb-org state=latest

  - name: Start mongodb
    service: name=mongod state=started
