---
  - name: Install mysql
    apt: pkg=mysql-server state=latest

  - name: Start mysql
    service: name=mysql state=started

  - name: Create users
    mysql_user: name={{ item }} password=gfhjkm priv={{ item }}_%.*:ALL state=present
    with_items: user_list
