---
- name: Setup user accounts
  user: name={{ item }} state=present groups=www-data
  with_items: user_list

- name: Create project folders
  file: path=/home/{{ item.0 }}/www/{{ item.1.name }} state=directory group={{ item.0 }} owner={{ item.0 }} recurse=yes
  with_nested:
    - user_list
    - all_project_list

- name: Create log folders
  file: path=/home/{{ item }}/log state=directory group={{ item }} owner={{ item }} recurse=yes
  with_items: user_list


- name: Give user rwx to his www dir
  file: path=/home/{{ item }}/www state=directory group={{ item }} owner={{ item }} recurse=yes
  with_items: user_list

# - name: Set default facl permissions for webserver
#   acl: name=/home/{{ item }}/www default=yes entity=www-data permissions=rwX etype=user state=present
#   with_items: user_list
#
# - name: Set facl permissions for webserver
#   acl: name=/home/{{ item }}/www entity=www-data permissions=rwX etype=user state=present
#   with_items: user_list

- name: Set default facl permissions for webserver
  acl: name=/home/{{ item }}/www entry="default:user:www-data:rwx" state=present
  with_items: user_list

- name: Set facl permissions for webserver
  acl: name=/home/{{ item }}/www entry="user:www-data:rwx" state=present
  with_items: user_list
